/**
 * ICAO airline designator → airline name lookup.
 * Covers major airlines worldwide. The callsign prefix (first 3 chars) maps to the airline.
 */
const AIRLINES = {
  AAL: 'American Airlines',
  AAR: 'Asiana Airlines',
  ACA: 'Air Canada',
  AFR: 'Air France',
  AIC: 'Air India',
  AIZ: 'Arkia Israeli Airlines',
  AJT: 'Amerijet International',
  AMX: 'Aeromexico',
  ANA: 'All Nippon Airways',
  ANZ: 'Air New Zealand',
  ASA: 'Alaska Airlines',
  AUA: 'Austrian Airlines',
  AUI: 'Ukraine Intl Airlines',
  AZA: 'Alitalia / ITA Airways',
  BAW: 'British Airways',
  BEL: 'Brussels Airlines',
  BER: 'Beriev Aircraft',
  CAL: 'China Airlines',
  CCA: 'Air China',
  CES: 'China Eastern',
  CFG: 'Condor',
  CLX: 'Cargolux',
  CPA: 'Cathay Pacific',
  CSN: 'China Southern',
  CTN: 'Croatia Airlines',
  CYP: 'Cyprus Airways',
  DAL: 'Delta Air Lines',
  DLH: 'Lufthansa',
  EAL: 'Eastern Airlines',
  EIN: 'Aer Lingus',
  EJU: 'easyJet Europe',
  ELY: 'El Al',
  ETH: 'Ethiopian Airlines',
  ETD: 'Etihad Airways',
  EVA: 'EVA Air',
  EWG: 'Eurowings',
  EZY: 'easyJet',
  FDX: 'FedEx Express',
  FIN: 'Finnair',
  FLI: 'Atlantic Airways',
  GEC: 'Lufthansa Cargo',
  GIA: 'Garuda Indonesia',
  GTI: 'Atlas Air',
  GWI: 'Germanwings',
  HAL: 'Hawaiian Airlines',
  HVN: 'Vietnam Airlines',
  IBE: 'Iberia',
  ICE: 'Icelandair',
  IGO: 'IndiGo',
  IRA: 'Iran Air',
  IRK: 'Iraero',
  JAL: 'Japan Airlines',
  JBU: 'JetBlue Airways',
  JST: 'Jetstar Airways',
  KAL: 'Korean Air',
  KLM: 'KLM Royal Dutch',
  KQA: 'Kenya Airways',
  LAN: 'LATAM Airlines',
  LOT: 'LOT Polish Airlines',
  MAH: 'Malev Hungarian',
  MAS: 'Malaysia Airlines',
  MSR: 'EgyptAir',
  NAX: 'Norwegian Air',
  NKS: 'Spirit Airlines',
  OAL: 'Olympic Air',
  PAC: 'Polar Air Cargo',
  PAL: 'Philippine Airlines',
  PGT: 'Pegasus Airlines',
  PIA: 'Pakistan Intl Airlines',
  QFA: 'Qantas',
  QTR: 'Qatar Airways',
  RAM: 'Royal Air Maroc',
  RJA: 'Royal Jordanian',
  ROT: 'TAROM',
  RYR: 'Ryanair',
  SAS: 'Scandinavian Airlines',
  SAA: 'South African Airways',
  SIA: 'Singapore Airlines',
  SKW: 'SkyWest Airlines',
  SWA: 'Southwest Airlines',
  SWR: 'Swiss Intl Air Lines',
  TAP: 'TAP Air Portugal',
  THA: 'Thai Airways',
  THY: 'Turkish Airlines',
  TUI: 'TUI fly',
  TVF: 'Transavia France',
  TWA: 'Trans World Airlines',
  UAE: 'Emirates',
  UAL: 'United Airlines',
  UPS: 'UPS Airlines',
  UTA: 'UTair Aviation',
  VIR: 'Virgin Atlantic',
  VOZ: 'Virgin Australia',
  VLG: 'Vueling Airlines',
  WZZ: 'Wizz Air',
  AEE: 'Aegean Airlines',
};

/**
 * Extract airline name from a callsign.
 * Returns the airline name or null if not found.
 */
export function getAirline(callsign) {
  if (!callsign || callsign.length < 3) return null;
  const prefix = callsign.substring(0, 3).toUpperCase();
  return AIRLINES[prefix] || null;
}
